Repository EdgePi-Cloud/edgepi-python-sdk, pull requests merged in 2022-12, with the labels that each got.

#197 remove integration test workflow
  .bumpversion.cfg
  .github/workflows/python-integration-test.yml
  setup.py
Labels: bug

#201 Update Dev Package Version
  .bumpversion.cfg
  .github/workflows/update-dev-version.yml
  setup.py
Labels: bug

#203 Fix Broken Module Links
  README.md
Labels: bug

#225 Digital_output module issue fix
  src/edgepi/digital_output/README.md
  src/edgepi/gpio/edgepi_gpio_chip.py
  src/edgepi/gpio/gpio_configs.py
  src/edgepi/peripherals/gpio.py
  src/test_edgepi/unit_tests/test_gpio/test_edgpepi_gpio_chip.py
Labels: GPIO, priority/P3, DIGITAL_I/O

#227 Update .bumpversion.cfg
  .bumpversion.cfg
Labels: CI/CD

#228 Digital out integration test
  tests/integration_tests/test_digital_out/__init__.py
  tests/integration_tests/test_digital_out/test_digital_out.py
Labels: CI/CD
